### ISSUE TITLE
max. recursion depth reached in automations?

### ISSUE THREAD

**Issue by CamDavidsonPilon** [Pioreactor/pioreactor#120]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/psutil/_common.py", line 447, in wrapper
    ret = self._cache[fun]
AttributeError: _cache

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pioreactor-21.5.0-py3.7.egg/pioreactor/utils/timing.py", line 64, in _target
    self.function(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pioreactor-21.5.0-py3.7.egg/pioreactor/background_jobs/subjobs/led_automation.py", line 98, in run
    return self.run()
  File "/usr/local/lib/python3.7/dist-packages/pioreactor-21.5.0-py3.7.egg/pioreactor/background_jobs/subjobs/led_automation.py", line 98, in run
    return self.run()
  File "/usr/local/lib/python3.7/dist-packages/pioreactor-21.5.0-py3.7.egg/pioreactor/background_jobs/subjobs/led_automation.py", line 98, in run
    return self.run()
  [Previous line repeated 972 more times]
  File "/usr/local/lib/python3.7/dist-packages/pioreactor-21.5.0-py3.7.egg/pioreactor/background_jobs/subjobs/led_automation.py", line 90, in run
    if not ("od_reading" in pio_jobs_running()) and (
  File "/usr/local/lib/python3.7/dist-packages/pioreactor-21.5.0-py3.7.egg/pioreactor/utils/__init__.py", line 8, in pio_jobs_running
    for proc in psutil.process_iter(attrs=["pid", "name", "cmdline"]):
  File "/usr/local/lib/python3.7/dist-packages/psutil/__init__.py", line 1443, in process_iter
    if proc.is_running():
  File "/usr/local/lib/python3.7/dist-packages/psutil/__init__.py", line 581, in is_running
    return self == Process(self.pid)
  File "/usr/local/lib/python3.7/dist-packages/psutil/__init__.py", line 326, in __init__
    self._init(pid)
  File "/usr/local/lib/python3.7/dist-packages/psutil/__init__.py", line 354, in _init
    self.create_time()
  File "/usr/local/lib/python3.7/dist-packages/psutil/__init__.py", line 710, in create_time
    self._create_time = self._proc.create_time()
  File "/usr/local/lib/python3.7/dist-packages/psutil/_pslinux.py", line 1576, in wrapper
    return fun(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/psutil/_pslinux.py", line 1788, in create_time
    ctime = float(self._parse_stat_file()['create_time'])
  File "/usr/local/lib/python3.7/dist-packages/psutil/_pslinux.py", line 1576, in wrapper
    return fun(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/psutil/_common.py", line 450, in wrapper
    return fun(self)
  File "/usr/local/lib/python3.7/dist-packages/psutil/_pslinux.py", line 1619, in _parse_stat_file
    data = f.read()
RecursionError: maximum recursion depth exceeded while calling a Python object|
```

**Comment by CamDavidsonPilon** [comment]
This should be fixed
