### ISSUE TITLE
Some new temp i2c errors

### ISSUE THREAD

**Issue by CamDavidsonPilon** [Pioreactor/pioreactor#315]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/pioreactor/background_jobs/temperature_control.py", line 219, in read_external_temperature
    running_sum += self.tmp_driver.get_temperature()
  File "/home/pioreactor/.local/lib/python3.9/site-packages/TMP1075/__init__.py", line 22, in get_temperature
    self.i2c.write_then_readinto(self.TEMP_REGISTER, b)
  File "/usr/local/lib/python3.9/dist-packages/adafruit_bus_device/i2c_device.py", line 139, in write_then_readinto
    self.i2c.writeto_then_readfrom(
  File "/usr/local/lib/python3.9/dist-packages/busio.py", line 186, in writeto_then_readfrom
    return self._i2c.writeto_then_readfrom(
  File "/usr/local/lib/python3.9/dist-packages/adafruit_blinka/microcontroller/generic_linux/i2c.py", line 90, in writeto_then_readfrom
    readin = self._i2c_bus.read_i2c_block_data(
  File "/usr/local/lib/python3.9/dist-packages/Adafruit_PureIO/smbus.py", line 275, in read_i2c_block_data
    ioctl(self._device.fileno(), I2C_RDWR, request)
OSError: [Errno 121] Remote I/O error

```

https://stackoverflow.com/questions/62757687/raspberry-pi-4-i2c-bus-not-working-correctly/62786449#62786449

**Comment by CamDavidsonPilon** [comment]
After making the change to the always use the register, having seen this in a few months.
